### ISSUE TITLE
CoreML not using GPU

### ISSUE THREAD

**Issue by Jasonsey** [pykeio/ort#341]
Hi there,

I'm running an onnx model useing CoreML. if I run this model in cargo I can see it's using gpu well, it spends about 40s to infer the model.

But If I build this model into Mac APP using cargo swfit crate, only cpu is used and it spends about 2min to infer the model. And also I try to infer the model using python onnxruntime, it spend about 10s.

this is a snapshot when I run this model in Mac APP. 

![Image](https://github.com/user-attachments/assets/27e723a2-44f6-4676-851f-0e11daee8215)

Any Idea that I can find why this happen or I can I solve this issue ?

**Comment by altunenes** [comment]
Have you found a solution? I think I reproduced this problem on this project

https://github.com/altunenes/scramblery/blob/main/onnx/Cargo.toml
https://github.com/altunenes/scramblery/blob/main/onnx/src/lib.rs

normally, since I just make some simple face detection on this project, I didn't bother to create different installers (and model is tiny) so I went full CPU, but internally, tried to run it via CoreML, and I see no GPU usage, at least according to activity monitor, . CUDA is working tho.

**Comment by mespencer** [comment]
I ran into this previously. The way I fixed it was to use the `main` branch, as the released versions don't have the required settings available. Then modify your execution provider to look similar to:
```rust
CoreMLExecutionProvider::default()
                .with_compute_units(coreml::CoreMLComputeUnits::All)
                .with_static_input_shapes(true)
                .with_model_format(coreml::CoreMLModelFormat::MLProgram)
                .with_specialization_strategy(coreml::CoreMLSpecializationStrategy::FastPrediction)
```

In reality, only one of those settings was required. However, this was several weeks ago and I can't remember which one made the difference. That said if you play around with these settings it should be pretty easy to figure out which one actually does it (I kind of think it was the compute units one).

Hope that helps!

**Comment by decahedron1** [comment]
[`v2.0.0-rc.10`](https://github.com/pykeio/ort/releases/tag/v2.0.0-rc.10) was released with a reworked CoreML EP interface supporting the options mentioned by @mespencer.

When it comes to CoreML, the most important factor for performance is minimizing graph splits, which occur when an ONNX operator is not supported by CoreML. The new `MLProgram` model format might have better compatibility for some models, so it's worth enabling that and testing your model's performance relative to the default `NeuralNetwork` format. Setting the compute units to `CoreMLComputeUnits::All` shouldn't hurt, though I think it might be the default, so I'm not sure if it would *help* either.

If you still see unexpected performance, enable the [`CoreMLExecutionProvider::with_profile_compute_plan`](https://docs.rs/ort/2.0.0-rc.10/ort/execution_providers/coreml/struct.CoreMLExecutionProvider.html#method.with_profile_compute_plan) option to log any graph splits that occur, and which device each operator ends up on (note that you'll probably have to lower `ort`'s log level via `tracing` to see the logs). Consult the [CoreML EP's docs](https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider.html#supported-operators) for the list of operators supported by CoreML, and if possible, rework your graph to remove any unsupported operators.
