### ISSUE TITLE
CUDA Error, QuickGeluFusion, named symbol not found

### ISSUE THREAD

**Issue by jeffrey-cochran** [pykeio/ort#540]
Hi y'all,

Love this crate; thank you for your work! I'm running into the following error when executing my model with the CUDA EP (it works fine with DirectML EP): 

> ERROR ort::logging: Non-zero status code returned while running QuickGelu node. Name:'/model.0/act/Mul/QuickGeluFusion/' Status Message: CUDA error cudaErrorSymbolNotFound:named symbol not found

I am using:

- Windows 11
- NVIDIA RTX 5090
- ort v2.0.0-rc.11
- CUDA v12.2
- CuDNN v9.19

I'm happy to try anything if you have thoughts about what might be the issue.

**Comment by decahedron1** [comment]
Sounds like the CUDA version is too old - binaries are built against CUDA v12.8. Would you be able to upgrade to 12.8 (or newer 12.x)? Otherwise, you'd have to build ONNX Runtime from source against 12.2.

**Comment by jeffrey-cochran** [comment]
> Sounds like the CUDA version is too old - binaries are built against CUDA v12.8. Would you be able to upgrade to 12.8 (or newer 12.x)? Otherwise, you'd have to build ONNX Runtime from source against 12.2.

I was wondering if that might be the issue. Thanks! I think I already have binaries for v12.8, and was linking to 12.2 for some other project (don't remember why). I'll give that a shot quickly and let you know.

**Comment by jeffrey-cochran** [comment]
> Sounds like the CUDA version is too old - binaries are built against CUDA v12.8. Would you be able to upgrade to 12.8 (or newer 12.x)? Otherwise, you'd have to build ONNX Runtime from source against 12.2.

I changed the path to point to CUDA 12.8 binaries, but I'm still getting the following error:

> ERROR ort::logging: Non-zero status code returned while running QuickGelu node. Name:'/model.0/act/Mul/QuickGeluFusion/' Status Message: CUDA error cudaErrorSymbolNotFound:named symbol not found 

Any chance this is an issue with ONNX Runtime v1.23? I've definitely run this model using CUDA and pytorch (not using ONNX format) in the past.

**Comment by decahedron1** [comment]
That would be my next suspicion. You could try with the `main` branch of `ort`, which is updated to 1.24.1. It has some breaking changes, but there's a good chance you won't run into those:
```toml
[dependencies]
ort = { git = "https://github.com/pykeio/ort.git", rev = "0fe5b252fdc74c719992c3e771331285a1d79e9c", features = [ "cuda" ] }
```

**Comment by jeffrey-cochran** [comment]
> That would be my next suspicion. You could try with the `main` branch of `ort`, which is updated to 1.24.1. It has some breaking changes, but there's a good chance you won't run into those:
> 
> [dependencies]
> ort = { git = "https://github.com/pykeio/ort.git", rev = "0fe5b252fdc74c719992c3e771331285a1d79e9c", features = [ "cuda" ] }

I'll give that a shot.

It also occurs to me that I recently updated my NVIDIA driver, and it looks like it's expecting CUDA v13.1. Might have to downgrade

> +---------------------------------------------------------------------------------------+
> | NVIDIA-SMI 591.74                 Driver Version: 591.74         CUDA Version: 13.1     |
> +-----------------------------------------+------------------------+-------------------+

**Comment by decahedron1** [comment]
`main` branch supports both CUDA 12 & 13! (though you might have to manually set the `ORT_CUDA_VERSION` environment variable to 12/13 if you have both installed)

**Comment by jeffrey-cochran** [comment]
> `main` branch supports both CUDA 12 & 13! (though you might have to manually set the `ORT_CUDA_VERSION` environment variable to 12/13 if you have both installed)

No luck so far (I tried with the `main` branch, and didn't hit any of the breaking changes, though, so that's good news 😄). I found a couple of other folks having the same issue with v1.23, and their solution was to downgrade to v1.22. So [I raised an issue over on ONNX Runtime's GitHub](https://github.com/microsoft/onnxruntime/issues/27504) to see if they had any thoughts. 

I'll try downgrading my NVIDIA driver real quick to see if that makes any difference. 

========================

UPDATE: downgrading the NVIDIA Driver did not fix anything. I'll use DirectML EP until I can figure out what's going on. Thanks for your help!

**Comment by jeffrey-cochran** [comment]
I think I figured out what was happening.

I had a CUDA/bin folder higher on PATH discovery than the lib directory, and I think that was masking the correct dlls.

In any case, I have it working now that I removed the bin directory from PATH.

==============

I'll probably package the dlls with the installer so that if people want to use CUDA they don't trip on it
