### ISSUE TITLE
Runtime failure trying to open libcublasLt.so.12 with cuda 13 installed

### ISSUE THREAD

**Issue by MathieuDuponchelle** [pykeio/ort#548]
I pushed a minimal reproduction example @ https://github.com/MathieuDuponchelle/ort-cuda-13-failure

Error is:

```
thread 'main' (462943) panicked at src/main.rs:6:8:
called `Result::unwrap()` on an `Err` value: Error { code: GenericFailure, message: "/home/runner/work/ort-artifacts/ort-artifacts/onnxruntime/onnxruntime/core/session/provider_bridge_ort.cc:1952 Provider &onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library /home/meh/devel/ort-cuda-13-fail/target/debug/libonnxruntime_providers_cuda.so with error: libcublasLt.so.12: cannot open shared object file: No such file or directory\n", ptr: 0x55e586ee5080 }
```

```
 meh   master  ~  devel  ort-cuda-13-fail  101  locate libcublasLt.so
/usr/local/cuda-13.1/targets/x86_64-linux/lib/libcublasLt.so
/usr/local/cuda-13.1/targets/x86_64-linux/lib/libcublasLt.so.13
/usr/local/cuda-13.1/targets/x86_64-linux/lib/libcublasLt.so.13.2.0.9
/usr/local/cuda-13.1/targets/x86_64-linux/lib/stubs/libcublasLt.so
```

Any ideas? Let me know if more information is needed!

**Comment by decahedron1** [comment]
Looks like `ort` wasn't able to detect your CUDA version & fell back to CUDA 12. You can override it by setting the `ORT_CUDA_VERSION` environment variable to `13` and rebuilding.

**Comment by MathieuDuponchelle** [comment]
Thanks, that works in that it then leads me to the next error, missing `libcudnn.so.9`, but I reckon that's only a problem on my end, the nvidia cuda repo apparently doesn't have cudnn builds for my distro (Fedora 42) :|

Feel free to close this but ooc how can I determine why ort fails to detect my CUDA version?

**Comment by decahedron1** [comment]
Yep, cuDNN 9.19 is also required. You can also install it [via tarball](https://developer.nvidia.com/cudnn-downloads?target_os=Linux&target_arch=x86_64&Distribution=Agnostic&cuda_version=13&Configuration=JIT).

The `CUDA_HOME` env var is probably missing (I don't think this is set by default) or `nvcc` isn't on path. Here's the detection code:

https://github.com/pykeio/ort/blob/56b32fddd8dc6acdc03fa714b18b751c4dc8e85e/ort-sys/build/download/resolve.rs#L37-L57

**Comment by MathieuDuponchelle** [comment]
thanks a bunch, sorry for the noise :)
